#! /usr/bin/env php
<?php

require __DIR__.'/./vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Csv to MySQL importer', '0.0.1');
$app->add(new Appkr\Importer\Command\CreateTableCommand);
$app->add(new Appkr\Importer\Command\DropTableCommand);
$app->add(new Appkr\Importer\Command\SelectTableCommand);
$app->add(new Appkr\Importer\Command\ImportCommand);
$app->run();